sudo: required

go_import_path: github.com/ory/dockertest/v3

language: go

services:
  - docker

go:
  - 1.13

install:
  - go get github.com/mattn/goveralls golang.org/x/tools/cmd/cover github.com/pierrre/gotestcover

script:
  - go vet -x .
  - go test -covermode=atomic -coverprofile="cover.out" .
  - goveralls -coverprofile="cover.out"
